version: '3.4'

services:
  db:
    image: web-api-aspnet-core5-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: dockerexample
      MYSQL_USER: docker
      MYSQL_PASSWORD: dockerexample
      MYSQL_DATABASE: cursowebapinet5
    ports:
      - 3308:3306
    networks: 
      - curso-udemy-network


  web-api-aspnet-core5:
    image: web-api-aspnet-core5
    build:
      context: .
      dockerfile: WebApiAspNetCore5/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 55394:80
    depends_on:
      - db
    networks: 
      - curso-udemy-network
networks: 
  curso-udemy-network:
    driver: bridge